### ISSUE TITLE
Peer To Peer Code Review

### ISSUE THREAD

**Issue by ouasamine** [Baayeh/awesome-books#4]
Hi, @Baayeh well done on the project ✔️ 👍🏽  after reviewing your project the team members had the following observations:

- Very clean and concise code well done on that ✔️ 
- Dividing the code into multiple methods is very good and effective ✔️ 
- Creating 2 classes to manage the booklist and the books objects is a very good approach ✔️

**Comment by Baayeh** [comment]
Thanks for the positive feedback. My partner and I are grateful 😃
